local os = loadstring(game:HttpGet("https://raw.githubusercontent.com/fxmmo/Nightfall-Storage/refs/heads/main/utils/modules/dev.lua"))()
local serialize = os:Import("https://raw.githubusercontent.com/fxmmo/InstanceForge/refs/heads/main/src/modules/serializer.lua")
local path = workspace.Baseplate

local code = {}

local date_time = DateTime.now:ToLocalTime()
local file_header = `--code generated by InstanceForge, file created on {date_time:FormatLocalTime("LL", "en-us")}`

local function identify_obj(obj)
  if obj:IsA("Model") then 
    serialize.model(obj) 
  elseif obj:IsA("Folder") then 
    serialize.folder(obj) 
  elseif obj:IsA("BasePart") then 
    serilocal.basepart 
  end 
end

local forge = {
  ToLuau = function(self, data)
  end
}